name: EAS build and upload

on:
  release:
    types: [released]

jobs:
  build:
    name: Create new build and upload to stores
    runs-on: ubuntu-latest
    env:
      APP_VERSION: ${{ github.event.release.tag_name }}
      RELEASE_BRANCH: release-${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name Daniel Grychtoł
          git config user.email grychtol.daniel@gmail.com
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install YARN
        run: npm -g install yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-i
      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install packages
        run: yarn install
      - name: Bump buildNumber and versionCode
        run: ./bin/bumper.sh
      - name: Add and commit
        run: |
          git checkout -b ${{ env.RELEASE_BRANCH }}
          git status
          git add app.json
          git commit -m "Update app.json"
          git push origin ${{ env.RELEASE_BRANCH }}
      - name: PR
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          source_branch: ${{ env.RELEASE_BRANCH }}
          pr_title: "[release] ${{ github.event.release.tag_name }}"
          pr_body: "🚀 Automated PR - build number and version code bump 🚀"
          pr_draft: false
          github_token: ${{ secrets.PAT }}
