name: Publish on Pull Request

on: [pull_request]

jobs:
  pr_build:
    name: Push to Expo Go on Pull Requests
    runs-on: ubuntu-latest
    env:
      RUN_NUMBER: ${{ github.run_number }}
      RELEASE_CHANNEL: "pr-${{ env.RUN_NUMBER }}"
      EXPO_PROJECT: "@daniel_grychtol/eas-cicd"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install YARN
        run: npm -g install yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-i
      - uses: expo/expo-github-action@v6
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true
          expo-version: 4.x
      - name: Install packages
        run: yarn install
      - name: EXPO Publish
        run: expo publish --non-interactive --release-channel ${{ env.RELEASE_CHANNEL }}
      - name: Add Comment To PR
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            ## 🚀 📲 Application preview
            ### Scan with your mobile:
            ![Expo QR](https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=exp://exp.host/${{ env.EXPO_PROJECT }}?release-channel=${{ env.RELEASE_CHANNEL }})
            ### or:
            Published to https://exp.host/${{ env.EXPO_PROJECT }}?release-channel=${{ env.RELEASE_CHANNEL }}
